/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register */
        post: operations["register_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/capture": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Capture */
        post: operations["capture_capture_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/snapshots/{snapshot_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Snapshot */
        get: operations["get_snapshot_snapshots__snapshot_id__get"];
        put?: never;
        post?: never;
        /** Delete Snapshot Route */
        delete: operations["delete_snapshot_route_snapshots__snapshot_id__delete"];
        options?: never;
        head?: never;
        /** Patch Snapshot */
        patch: operations["patch_snapshot_snapshots__snapshot_id__patch"];
        trace?: never;
    };
    "/snapshots/{snapshot_id}/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Snapshot Tag */
        post: operations["add_snapshot_tag_snapshots__snapshot_id__tags_post"];
        /** Remove Snapshot Tag */
        delete: operations["remove_snapshot_tag_snapshots__snapshot_id__tags_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/snapshots/{snapshot_id}/cards/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate Cards Route */
        post: operations["generate_cards_route_snapshots__snapshot_id__cards_generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/snapshots/{snapshot_id}/cards/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Export Cards Job Route */
        post: operations["export_cards_job_route_snapshots__snapshot_id__cards_export_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/snapshots/{snapshot_id}/cards/job": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download Cards Job Route */
        get: operations["download_cards_job_route"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        /** Download Cards Job Route */
        head: operations["head_cards_job_route"];
        patch?: never;
        trace?: never;
    };
    "/snapshots/{snapshot_id}/cards/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import Cards Route */
        post: operations["import_cards_route_snapshots__snapshot_id__cards_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/snapshots/{snapshot_id}/cards": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Cards Route */
        get: operations["list_cards_route_snapshots__snapshot_id__cards_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/snapshots/{snapshot_id}/cards/{card_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Card Route */
        delete: operations["delete_card_route_snapshots__snapshot_id__cards__card_id__delete"];
        options?: never;
        head?: never;
        /** Update Card Route */
        patch: operations["update_card_route_snapshots__snapshot_id__cards__card_id__patch"];
        trace?: never;
    };
    "/snapshots/{snapshot_id}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Export Snapshot */
        post: operations["export_snapshot_snapshots__snapshot_id__export_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/snapshots/{snapshot_id}/job": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download Job */
        get: operations["download_job_snapshots__snapshot_id__job_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/snapshots/{snapshot_id}/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import Snapshot */
        post: operations["import_snapshot_snapshots__snapshot_id__import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/subscriptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Subscriptions */
        get: operations["list_subscriptions_subscriptions_get"];
        put?: never;
        /** Create Subscription */
        post: operations["create_subscription_subscriptions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/subscriptions/{sub_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Subscription */
        delete: operations["delete_subscription_subscriptions__sub_id__delete"];
        options?: never;
        head?: never;
        /** Patch Subscription */
        patch: operations["patch_subscription_subscriptions__sub_id__patch"];
        trace?: never;
    };
    "/subscriptions/{sub_id}/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh Subscription */
        post: operations["refresh_subscription_subscriptions__sub_id__refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/subscriptions/{sub_id}/read-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Read All */
        post: operations["read_all_subscriptions__sub_id__read_all_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/subscriptions/{sub_id}/entries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Subscription Entries */
        get: operations["subscription_entries_subscriptions__sub_id__entries_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/feed-entries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** All Entries */
        get: operations["all_entries_feed_entries_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/feed-entries/{entry_id}/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark Read */
        post: operations["mark_read_feed_entries__entry_id__read_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/feed-entries/{entry_id}/unread": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark Unread */
        post: operations["mark_unread_feed_entries__entry_id__unread_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/feed-entries/{entry_id}/gulp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Gulp Entry */
        post: operations["gulp_entry_feed_entries__entry_id__gulp_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/feeds/catalog/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Catalog Search */
        get: operations["catalog_search_feeds_catalog_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/snapshots/{snapshot_id}/figures": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Figures Route */
        get: operations["list_figures_route_snapshots__snapshot_id__figures_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/snapshots/{snapshot_id}/figures/{figure_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Figure Route */
        get: operations["get_figure_route_snapshots__snapshot_id__figures__figure_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gulp/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Session */
        post: operations["start_session_gulp_sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gulp/sessions/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Current */
        get: operations["get_current_gulp_sessions_current_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gulp/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Session */
        get: operations["get_session_gulp_sessions__session_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gulp/sessions/{session_id}/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Review */
        post: operations["review_gulp_sessions__session_id__reviews_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gulp/sessions/{session_id}/snooze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Snooze */
        post: operations["snooze_gulp_sessions__session_id__snooze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gulp/sessions/{session_id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Complete */
        post: operations["complete_gulp_sessions__session_id__complete_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gulp/sessions/{session_id}/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Summary */
        get: operations["summary_gulp_sessions__session_id__summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/inbox": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Inbox */
        get: operations["inbox_inbox_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/library": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Library */
        get: operations["get_library_library_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/snapshots/{snapshot_id}/pack": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Pack */
        get: operations["get_pack_snapshots__snapshot_id__pack_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/snapshots/{snapshot_id}/blocks/{block_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Block Route */
        delete: operations["delete_block_route_snapshots__snapshot_id__blocks__block_id__delete"];
        options?: never;
        head?: never;
        /** Update Block Route */
        patch: operations["update_block_route_snapshots__snapshot_id__blocks__block_id__patch"];
        trace?: never;
    };
    "/snapshots/{snapshot_id}/sections/{section_id}/blocks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Block Route */
        post: operations["create_block_route_snapshots__snapshot_id__sections__section_id__blocks_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/snapshots/{snapshot_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Messages Route */
        get: operations["list_messages_route_snapshots__snapshot_id__messages_get"];
        put?: never;
        /** Post Message Route */
        post: operations["post_message_route_snapshots__snapshot_id__messages_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/snapshots/{snapshot_id}/process": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Process Snapshot Endpoint */
        post: operations["process_snapshot_endpoint_snapshots__snapshot_id__process_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/today": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Today */
        get: operations["get_today_today_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BlockCreate */
        BlockCreate: {
            /** Content */
            content: components["schemas"]["ProseWrite"] | components["schemas"]["FormulaWrite"] | components["schemas"]["TableWrite"] | components["schemas"]["FigureWrite"] | components["schemas"]["ListWrite"] | components["schemas"]["CodeWrite"];
            /** Position */
            position: number;
        };
        /** BlockUpdate */
        BlockUpdate: {
            /** Content */
            content?: (components["schemas"]["ProseWrite"] | components["schemas"]["FormulaWrite"] | components["schemas"]["TableWrite"] | components["schemas"]["FigureWrite"] | components["schemas"]["ListWrite"] | components["schemas"]["CodeWrite"]) | null;
            /** Position */
            position?: number | null;
        };
        /** Body_import_snapshot_snapshots__snapshot_id__import_post */
        Body_import_snapshot_snapshots__snapshot_id__import_post: {
            /** File */
            file: string;
        };
        /** CaptureRequest */
        CaptureRequest: {
            /** Url */
            url?: string | null;
            /** Text */
            text?: string | null;
            /** Note */
            note?: string | null;
            /** Title */
            title?: string | null;
            /**
             * Tags
             * @default []
             */
            tags: string[];
            /** @default in_app */
            captured_via: components["schemas"]["CapturedVia"];
        };
        /** CaptureResponse */
        CaptureResponse: {
            snapshot: components["schemas"]["SnapshotOut"];
            /** Duplicate */
            duplicate: boolean;
        };
        /**
         * CapturedVia
         * @enum {string}
         */
        CapturedVia: "share_sheet" | "wechat" | "email" | "in_app" | "paste" | "manual" | "screenshot" | "audio_memo" | "feed";
        /** CardDraft */
        CardDraft: {
            card_type: components["schemas"]["CardType"];
            /** Prompt */
            prompt: string;
            /** Answer */
            answer?: string | null;
            /** Explanation */
            explanation?: string | null;
            /** Options */
            options?: string[] | null;
        };
        /** CardMasteryOut */
        CardMasteryOut: {
            /** Ladder */
            ladder: string;
            /** Daily */
            daily: string;
            /** Next Review At */
            next_review_at: string | null;
            /** Interval Days */
            interval_days: number;
        };
        /**
         * CardOrigin
         * @enum {string}
         */
        CardOrigin: "pack" | "conversation" | "user" | "imported";
        /** CardOut */
        CardOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            card_type: components["schemas"]["CardType"];
            /** Prompt */
            prompt: string;
            /** Answer */
            answer: string | null;
            /** Explanation */
            explanation: string | null;
            /** Options */
            options: string[] | null;
            origin: components["schemas"]["CardOrigin"];
            status: components["schemas"]["CardStatus"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Daily */
            daily?: ("new" | "learning" | "known") | null;
        };
        /**
         * CardPatch
         * @description Partial update; provided content fields are re-validated per card type.
         */
        CardPatch: {
            status?: components["schemas"]["CardStatus"] | null;
            /** Prompt */
            prompt?: string | null;
            /** Answer */
            answer?: string | null;
            /** Explanation */
            explanation?: string | null;
            /** Options */
            options?: string[] | null;
        };
        /**
         * CardStatus
         * @enum {string}
         */
        CardStatus: "draft" | "accepted" | "rejected";
        /**
         * CardType
         * @enum {string}
         */
        CardType: "flashcard" | "mcq" | "cloze";
        /** CardsPayload */
        CardsPayload: {
            /** Cards */
            cards: components["schemas"]["CardDraft"][];
        };
        /**
         * CardsStatus
         * @description Inline card-generation job state; null = never triggered. Imports don't touch it.
         * @enum {string}
         */
        CardsStatus: "generating" | "ready" | "failed";
        /** CatalogRouteOut */
        CatalogRouteOut: {
            /** Namespace */
            namespace: string;
            /** Namespace Name */
            namespace_name: string;
            /** Route Path */
            route_path: string;
            /** Route Name */
            route_name: string | null;
            /** Example */
            example: string | null;
            /** Parameters */
            parameters: {
                [key: string]: string;
            } | null;
            /** Require Config */
            require_config: boolean;
            /** Heat */
            heat: number;
        };
        /** CatalogSearchOut */
        CatalogSearchOut: {
            /** Items */
            items: components["schemas"]["CatalogRouteOut"][];
            /** Count */
            count: number;
        };
        /** CodeBlockOut */
        CodeBlockOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "code";
            /** Language */
            language?: string | null;
            /** Content */
            content: string;
        };
        /** CodeWrite */
        CodeWrite: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "code";
            /** Language */
            language?: string | null;
            /** Content */
            content: string;
        };
        /** FeedEntriesOut */
        FeedEntriesOut: {
            /** Items */
            items: components["schemas"]["FeedEntryOut"][];
            /** Count */
            count: number;
        };
        /** FeedEntryOut */
        FeedEntryOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Subscription Id
             * Format: uuid
             */
            subscription_id: string;
            /** Subscription Title */
            subscription_title: string;
            /** Title */
            title: string;
            /** Url */
            url: string | null;
            /** Author */
            author: string | null;
            /** Published At */
            published_at: string | null;
            /** Content Html */
            content_html: string | null;
            /** Read */
            read: boolean;
            /** Promoted Source Id */
            promoted_source_id: string | null;
            promoted_status: components["schemas"]["SnapshotStatus"] | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** FigureAssetOut */
        FigureAssetOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Label */
            label: string | null;
            /** Caption */
            caption: string | null;
            /** Mime Type */
            mime_type: string;
            /** Width */
            width: number | null;
            /** Height */
            height: number | null;
        };
        /** FigureBlockOut */
        FigureBlockOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "figure";
            /** Label */
            label: string;
            /** Explanation */
            explanation: string;
            /** Figure Id */
            figure_id?: string | null;
            /** Url */
            url?: string | null;
        };
        /** FigureWrite */
        FigureWrite: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "figure";
            /** Label */
            label: string;
            /** Explanation */
            explanation: string;
            /** Figure Id */
            figure_id?: string | null;
            /** Url */
            url?: string | null;
        };
        /** FormulaBlockOut */
        FormulaBlockOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "formula";
            /** Latex */
            latex: string;
            /** Explanation */
            explanation: string;
        };
        /** FormulaWrite */
        FormulaWrite: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "formula";
            /** Latex */
            latex: string;
            /** Explanation */
            explanation: string;
        };
        /** GulpEntryResponse */
        GulpEntryResponse: {
            /**
             * Snapshot Id
             * Format: uuid
             */
            snapshot_id: string;
            /** Duplicate */
            duplicate: boolean;
            status: components["schemas"]["SnapshotStatus"];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** InboxOut */
        InboxOut: {
            /** Items */
            items: components["schemas"]["SnapshotOut"][];
            /** Count */
            count: number;
        };
        /** LibraryOut */
        LibraryOut: {
            /** Items */
            items: components["schemas"]["SnapshotOut"][];
            /** Count */
            count: number;
        };
        /** ListBlockOut */
        ListBlockOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "list";
            /** Items */
            items: string[];
            /**
             * Ordered
             * @default false
             */
            ordered: boolean;
        };
        /** ListWrite */
        ListWrite: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "list";
            /** Items */
            items: string[];
            /**
             * Ordered
             * @default false
             */
            ordered: boolean;
        };
        /**
         * Locale
         * @enum {string}
         */
        Locale: "zh" | "en";
        /** LoginRequest */
        LoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** MasteryTally */
        MasteryTally: {
            /** New */
            new: number;
            /** Learning */
            learning: number;
            /** Known */
            known: number;
            /** At Risk */
            at_risk: number;
        };
        /**
         * MediaType
         * @enum {string}
         */
        MediaType: "article" | "pdf" | "video" | "podcast" | "note" | "screenshot" | "audio" | "webpage";
        /** MessageCreate */
        MessageCreate: {
            /** Content */
            content: string;
            /**
             * Block Refs
             * @default []
             */
            block_refs: string[];
        };
        /** MessageOut */
        MessageOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Role */
            role: string;
            /** Content */
            content: string;
            /** Block Refs */
            block_refs: string[];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** NextUp */
        NextUp: {
            /** Due Count */
            due_count: number;
            /** Inbox Count */
            inbox_count: number;
        };
        /** PackOut */
        PackOut: {
            /**
             * Snapshot Id
             * Format: uuid
             */
            snapshot_id: string;
            status: components["schemas"]["PackStatus"];
            pack_type: components["schemas"]["PackType"];
            /** Title */
            title: string;
            /** Summary */
            summary?: string | null;
            /**
             * Core Contributions
             * @default []
             */
            core_contributions: string[];
            /** Key Insight */
            key_insight?: string | null;
            /** Sections */
            sections: components["schemas"]["PackSectionOut"][];
            /**
             * References
             * @default []
             */
            references: components["schemas"]["PackReferenceOut"][];
        };
        /** PackReferenceOut */
        PackReferenceOut: {
            /** Citation */
            citation: string;
            /** Why Interesting */
            why_interesting: string;
        };
        /** PackSectionOut */
        PackSectionOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Heading */
            heading: string | null;
            /** Blocks */
            blocks: (components["schemas"]["ProseBlockOut"] | components["schemas"]["FormulaBlockOut"] | components["schemas"]["TableBlockOut"] | components["schemas"]["FigureBlockOut"] | components["schemas"]["ListBlockOut"] | components["schemas"]["CodeBlockOut"])[];
        };
        /**
         * PackStatus
         * @enum {string}
         */
        PackStatus: "generating" | "ready";
        /**
         * PackType
         * @description Discriminator selecting the pack implementation (docs/02 §4.4):
         *     `paper` = LLM-authored deep report; `article` = deterministic preserve
         *     of the source's own structure.
         * @enum {string}
         */
        PackType: "paper" | "article";
        /** ProseBlockOut */
        ProseBlockOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "prose";
            /** Content */
            content: string;
        };
        /** ProseWrite */
        ProseWrite: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "prose";
            /** Content */
            content: string;
        };
        /** RegisterRequest */
        RegisterRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
            /** Display Name */
            display_name?: string | null;
            /** @default en */
            locale: components["schemas"]["Locale"];
        };
        /** ReviewIn */
        ReviewIn: {
            /**
             * Card Id
             * Format: uuid
             */
            card_id: string;
            /**
             * Grade
             * @enum {string}
             */
            grade: "got_it" | "fuzzy" | "missed";
            /** Response */
            response?: string | null;
        };
        /** ReviewOut */
        ReviewOut: {
            mastery: components["schemas"]["CardMasteryOut"];
            next_card: components["schemas"]["SessionCardOut"] | null;
            /** Done */
            done: boolean;
        };
        /** SessionCardOut */
        SessionCardOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Card Type
             * @enum {string}
             */
            card_type: "flashcard" | "mcq" | "cloze";
            /** Prompt */
            prompt: string;
            /** Options */
            options?: string[] | null;
            /** Answer */
            answer?: string | null;
            /** Explanation */
            explanation?: string | null;
            /** Source Title */
            source_title?: string | null;
            /**
             * Reason
             * @enum {string}
             */
            reason: "new" | "due" | "retest" | "at_risk";
            /**
             * Daily
             * @enum {string}
             */
            daily: "new" | "learning" | "known";
        };
        /** SessionOut */
        SessionOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Scope Type */
            scope_type: string;
            /** Target Minutes */
            target_minutes: number;
            /** Status */
            status: string;
            /** Started At */
            started_at: string | null;
            /** Cards */
            cards: components["schemas"]["SessionCardOut"][];
        };
        /** SessionStartIn */
        SessionStartIn: {
            /**
             * Scope Type
             * @default daily
             * @enum {string}
             */
            scope_type: "daily" | "at_risk" | "free_explore";
            /** Target Minutes */
            target_minutes?: number | null;
        };
        /** SnapshotOut */
        SnapshotOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            kind: components["schemas"]["SourceKind"];
            /** Title */
            title: string;
            /** Note */
            note: string | null;
            status: components["schemas"]["SnapshotStatus"];
            media_type: components["schemas"]["MediaType"] | null;
            genre: components["schemas"]["SourceGenre"] | null;
            /** Origin Url */
            origin_url: string | null;
            /** Content Body */
            content_body: string | null;
            captured_via: components["schemas"]["CapturedVia"] | null;
            cards_status: components["schemas"]["CardsStatus"] | null;
            /** Tags */
            tags: string[];
            source_feed?: components["schemas"]["SourceFeedOut"] | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * SnapshotPatch
         * @description Curation-time corrections; genre re-selects the processing strategy on
         *     the next re-run.
         */
        SnapshotPatch: {
            genre: components["schemas"]["SourceGenre"];
        };
        /**
         * SnapshotStatus
         * @description Single-gate lifecycle: `ready` IS "in the library" — the snapshot-level
         *     review gate is parked (spec 2026-07-02-single-gate-lifecycle-design.md).
         * @enum {string}
         */
        SnapshotStatus: "queued" | "unprocessed" | "processing" | "ready" | "exported" | "needs_attention";
        /** SnoozeIn */
        SnoozeIn: {
            /**
             * Card Id
             * Format: uuid
             */
            card_id: string;
        };
        /**
         * SourceFeedOut
         * @description The subscription feed that produced a snapshot (derived from
         *     Source.emitted_by); null for ad-hoc captures.
         */
        SourceFeedOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
        };
        /**
         * SourceGenre
         * @description Knowledge genre — what kind of knowledge artifact this is, not the media
         *     format (that is `MediaType`). Detected at parse time, user-correctable;
         *     selects the pack-production strategy (docs/02 §4.3-4.4).
         * @enum {string}
         */
        SourceGenre: "paper" | "article" | "note";
        /**
         * SourceKind
         * @enum {string}
         */
        SourceKind: "snapshot" | "conversation" | "subscription";
        /** SubscriptionCreate */
        SubscriptionCreate: {
            /** Feed Url */
            feed_url: string;
            /** Title */
            title?: string | null;
        };
        /** SubscriptionCreateResponse */
        SubscriptionCreateResponse: {
            subscription: components["schemas"]["SubscriptionOut"];
            /** Duplicate */
            duplicate: boolean;
        };
        /** SubscriptionOut */
        SubscriptionOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
            /** Feed Url */
            feed_url: string;
            /**
             * Health
             * @enum {string}
             */
            health: "active" | "muted" | "error";
            /** Muted */
            muted: boolean;
            /** Unread Count */
            unread_count: number;
            /** Last Fetch At */
            last_fetch_at: string | null;
            /** Last Fetch Error */
            last_fetch_error: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** SubscriptionPatch */
        SubscriptionPatch: {
            /** Title */
            title?: string | null;
            /** Muted */
            muted?: boolean | null;
        };
        /** SubscriptionsOut */
        SubscriptionsOut: {
            /** Items */
            items: components["schemas"]["SubscriptionOut"][];
            /** Count */
            count: number;
        };
        /** SummaryOut */
        SummaryOut: {
            /** Reviewed Count */
            reviewed_count: number;
            /** Newly Mastered */
            newly_mastered: number;
            /** Still Fuzzy */
            still_fuzzy: number;
            /** Streak Days */
            streak_days: number;
            next_up: components["schemas"]["NextUp"];
        };
        /** TableBlockOut */
        TableBlockOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "table";
            /** Headers */
            headers: string[];
            /** Rows */
            rows: string[][];
            /** Caption */
            caption?: string | null;
        };
        /** TableWrite */
        TableWrite: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "table";
            /** Headers */
            headers: string[];
            /** Rows */
            rows: string[][];
            /** Caption */
            caption?: string | null;
        };
        /** TagCreate */
        TagCreate: {
            /** Tag */
            tag: string;
        };
        /** TodayDigestItem */
        TodayDigestItem: {
            snapshot: components["schemas"]["SnapshotOut"];
            /** Accepted Cards */
            accepted_cards: number;
        };
        /** TodayOut */
        TodayOut: {
            /** Accepted Cards */
            accepted_cards: number;
            /** Card Sources */
            card_sources: number;
            /** Ready Count */
            ready_count: number;
            /** Digest */
            digest: components["schemas"]["TodayDigestItem"][];
            /** Inbox Count */
            inbox_count: number;
            /** Recent */
            recent: components["schemas"]["SnapshotOut"][];
            /** Due Count */
            due_count: number;
            /** New Count */
            new_count: number;
            mastery: components["schemas"]["MasteryTally"];
        };
        /** UserPublic */
        UserPublic: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Email */
            email: string;
            /** Display Name */
            display_name: string | null;
            locale: components["schemas"]["Locale"];
            /** Gulp Session Minutes */
            gulp_session_minutes: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    register_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPublic"];
                };
            };
        };
    };
    capture_capture_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CaptureRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaptureResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_snapshot_snapshots__snapshot_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                snapshot_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnapshotOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_snapshot_route_snapshots__snapshot_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                snapshot_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_snapshot_snapshots__snapshot_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                snapshot_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SnapshotPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnapshotOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_snapshot_tag_snapshots__snapshot_id__tags_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                snapshot_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TagCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnapshotOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_snapshot_tag_snapshots__snapshot_id__tags_delete: {
        parameters: {
            query: {
                tag: string;
            };
            header?: never;
            path: {
                snapshot_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnapshotOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_cards_route_snapshots__snapshot_id__cards_generate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                snapshot_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnapshotOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_cards_job_route_snapshots__snapshot_id__cards_export_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                snapshot_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnapshotOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_cards_job_route: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                snapshot_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    head_cards_job_route: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                snapshot_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_cards_route_snapshots__snapshot_id__cards_import_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                snapshot_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CardsPayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CardOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_cards_route_snapshots__snapshot_id__cards_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                snapshot_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CardOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_card_route_snapshots__snapshot_id__cards__card_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                snapshot_id: string;
                card_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_card_route_snapshots__snapshot_id__cards__card_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                snapshot_id: string;
                card_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CardPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CardOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_snapshot_snapshots__snapshot_id__export_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                snapshot_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnapshotOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_job_snapshots__snapshot_id__job_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                snapshot_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_snapshot_snapshots__snapshot_id__import_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                snapshot_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_import_snapshot_snapshots__snapshot_id__import_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnapshotOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_subscriptions_subscriptions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubscriptionsOut"];
                };
            };
        };
    };
    create_subscription_subscriptions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubscriptionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubscriptionCreateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_subscription_subscriptions__sub_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sub_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_subscription_subscriptions__sub_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sub_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubscriptionPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubscriptionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_subscription_subscriptions__sub_id__refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sub_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_all_subscriptions__sub_id__read_all_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sub_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    subscription_entries_subscriptions__sub_id__entries_get: {
        parameters: {
            query?: {
                unread_only?: boolean;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                sub_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedEntriesOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    all_entries_feed_entries_get: {
        parameters: {
            query?: {
                unread_only?: boolean;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedEntriesOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mark_read_feed_entries__entry_id__read_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entry_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mark_unread_feed_entries__entry_id__unread_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entry_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    gulp_entry_feed_entries__entry_id__gulp_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entry_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GulpEntryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    catalog_search_feeds_catalog_search_get: {
        parameters: {
            query?: {
                q?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogSearchOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_figures_route_snapshots__snapshot_id__figures_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                snapshot_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FigureAssetOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_figure_route_snapshots__snapshot_id__figures__figure_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                snapshot_id: string;
                figure_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_session_gulp_sessions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SessionStartIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_current_gulp_sessions_current_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionOut"] | null;
                };
            };
        };
    };
    get_session_gulp_sessions__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    review_gulp_sessions__session_id__reviews_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    snooze_gulp_sessions__session_id__snooze_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SnoozeIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    complete_gulp_sessions__session_id__complete_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SummaryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    summary_gulp_sessions__session_id__summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SummaryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    inbox_inbox_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InboxOut"];
                };
            };
        };
    };
    get_library_library_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LibraryOut"];
                };
            };
        };
    };
    get_pack_snapshots__snapshot_id__pack_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                snapshot_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PackOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_block_route_snapshots__snapshot_id__blocks__block_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                snapshot_id: string;
                block_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_block_route_snapshots__snapshot_id__blocks__block_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                snapshot_id: string;
                block_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BlockUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProseBlockOut"] | components["schemas"]["FormulaBlockOut"] | components["schemas"]["TableBlockOut"] | components["schemas"]["FigureBlockOut"] | components["schemas"]["ListBlockOut"] | components["schemas"]["CodeBlockOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_block_route_snapshots__snapshot_id__sections__section_id__blocks_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                snapshot_id: string;
                section_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BlockCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProseBlockOut"] | components["schemas"]["FormulaBlockOut"] | components["schemas"]["TableBlockOut"] | components["schemas"]["FigureBlockOut"] | components["schemas"]["ListBlockOut"] | components["schemas"]["CodeBlockOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_messages_route_snapshots__snapshot_id__messages_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                snapshot_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_message_route_snapshots__snapshot_id__messages_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                snapshot_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MessageCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    process_snapshot_endpoint_snapshots__snapshot_id__process_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                snapshot_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnapshotOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_today_today_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TodayOut"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
