/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/capture": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Capture */
        post: operations["capture_capture_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/snapshots/{snapshot_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Snapshot */
        get: operations["get_snapshot_snapshots__snapshot_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/snapshots/{snapshot_id}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Export Snapshot */
        post: operations["export_snapshot_snapshots__snapshot_id__export_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/snapshots/{snapshot_id}/job": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download Job */
        get: operations["download_job_snapshots__snapshot_id__job_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/snapshots/{snapshot_id}/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import Snapshot */
        post: operations["import_snapshot_snapshots__snapshot_id__import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/inbox": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Inbox */
        get: operations["inbox_inbox_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/snapshots/{snapshot_id}/pack": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Pack */
        get: operations["get_pack_snapshots__snapshot_id__pack_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/snapshots/{snapshot_id}/blocks/{block_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Block Route */
        delete: operations["delete_block_route_snapshots__snapshot_id__blocks__block_id__delete"];
        options?: never;
        head?: never;
        /** Update Block Route */
        patch: operations["update_block_route_snapshots__snapshot_id__blocks__block_id__patch"];
        trace?: never;
    };
    "/snapshots/{snapshot_id}/sections/{section_id}/blocks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Block Route */
        post: operations["create_block_route_snapshots__snapshot_id__sections__section_id__blocks_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/snapshots/{snapshot_id}/process": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Process Snapshot Endpoint */
        post: operations["process_snapshot_endpoint_snapshots__snapshot_id__process_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BlockCreate */
        BlockCreate: {
            /** Content */
            content: components["schemas"]["ProseWrite"] | components["schemas"]["FormulaWrite"] | components["schemas"]["TableWrite"] | components["schemas"]["FigureWrite"] | components["schemas"]["ListWrite"];
            /** Position */
            position: number;
        };
        /** BlockUpdate */
        BlockUpdate: {
            /** Content */
            content?: (components["schemas"]["ProseWrite"] | components["schemas"]["FormulaWrite"] | components["schemas"]["TableWrite"] | components["schemas"]["FigureWrite"] | components["schemas"]["ListWrite"]) | null;
            /** Position */
            position?: number | null;
        };
        /** Body_import_snapshot_snapshots__snapshot_id__import_post */
        Body_import_snapshot_snapshots__snapshot_id__import_post: {
            /** File */
            file: string;
        };
        /** CaptureRequest */
        CaptureRequest: {
            /** Url */
            url?: string | null;
            /** Text */
            text?: string | null;
            /** Note */
            note?: string | null;
            /** Title */
            title?: string | null;
            /**
             * Tags
             * @default []
             */
            tags: string[];
            /** @default in_app */
            captured_via: components["schemas"]["CapturedVia"];
        };
        /** CaptureResponse */
        CaptureResponse: {
            snapshot: components["schemas"]["SnapshotOut"];
            /** Duplicate */
            duplicate: boolean;
        };
        /**
         * CapturedVia
         * @enum {string}
         */
        CapturedVia: "share_sheet" | "wechat" | "email" | "in_app" | "paste" | "manual" | "screenshot" | "audio_memo";
        /** FigureBlockOut */
        FigureBlockOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "figure";
            /** Label */
            label: string;
            /** Explanation */
            explanation: string;
        };
        /** FigureWrite */
        FigureWrite: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "figure";
            /** Label */
            label: string;
            /** Explanation */
            explanation: string;
        };
        /** FormulaBlockOut */
        FormulaBlockOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "formula";
            /** Latex */
            latex: string;
            /** Explanation */
            explanation: string;
        };
        /** FormulaWrite */
        FormulaWrite: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "formula";
            /** Latex */
            latex: string;
            /** Explanation */
            explanation: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** InboxOut */
        InboxOut: {
            /** Items */
            items: components["schemas"]["SnapshotOut"][];
            /** Count */
            count: number;
        };
        /** ListBlockOut */
        ListBlockOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "list";
            /** Items */
            items: string[];
            /**
             * Ordered
             * @default false
             */
            ordered: boolean;
        };
        /** ListWrite */
        ListWrite: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "list";
            /** Items */
            items: string[];
            /**
             * Ordered
             * @default false
             */
            ordered: boolean;
        };
        /**
         * MediaType
         * @enum {string}
         */
        MediaType: "article" | "pdf" | "video" | "podcast" | "note" | "screenshot" | "audio" | "webpage";
        /** PackOut */
        PackOut: {
            /**
             * Snapshot Id
             * Format: uuid
             */
            snapshot_id: string;
            status: components["schemas"]["PackStatus"];
            /** Title */
            title: string;
            /** Core Contributions */
            core_contributions: string[];
            /** Key Insight */
            key_insight: string;
            /** Sections */
            sections: components["schemas"]["PackSectionOut"][];
            /** References */
            references: components["schemas"]["PackReferenceOut"][];
        };
        /** PackReferenceOut */
        PackReferenceOut: {
            /** Citation */
            citation: string;
            /** Why Interesting */
            why_interesting: string;
        };
        /** PackSectionOut */
        PackSectionOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Heading */
            heading: string | null;
            /** Blocks */
            blocks: (components["schemas"]["ProseBlockOut"] | components["schemas"]["FormulaBlockOut"] | components["schemas"]["TableBlockOut"] | components["schemas"]["FigureBlockOut"] | components["schemas"]["ListBlockOut"])[];
        };
        /**
         * PackStatus
         * @enum {string}
         */
        PackStatus: "generating" | "ready";
        /** ProseBlockOut */
        ProseBlockOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "prose";
            /** Content */
            content: string;
        };
        /** ProseWrite */
        ProseWrite: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "prose";
            /** Content */
            content: string;
        };
        /** SnapshotOut */
        SnapshotOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            kind: components["schemas"]["SourceKind"];
            /** Title */
            title: string;
            /** Note */
            note: string | null;
            status: components["schemas"]["SnapshotStatus"];
            media_type: components["schemas"]["MediaType"] | null;
            /** Origin Url */
            origin_url: string | null;
            /** Content Body */
            content_body: string | null;
            captured_via: components["schemas"]["CapturedVia"] | null;
            /** Tags */
            tags: string[];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * SnapshotStatus
         * @enum {string}
         */
        SnapshotStatus: "queued" | "unprocessed" | "processing" | "ready" | "exported" | "awaiting_review" | "in_library" | "needs_attention";
        /**
         * SourceKind
         * @enum {string}
         */
        SourceKind: "snapshot" | "conversation" | "subscription";
        /** TableBlockOut */
        TableBlockOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "table";
            /** Headers */
            headers: string[];
            /** Rows */
            rows: string[][];
            /** Caption */
            caption?: string | null;
        };
        /** TableWrite */
        TableWrite: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "table";
            /** Headers */
            headers: string[];
            /** Rows */
            rows: string[][];
            /** Caption */
            caption?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    capture_capture_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CaptureRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaptureResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_snapshot_snapshots__snapshot_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                snapshot_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnapshotOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_snapshot_snapshots__snapshot_id__export_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                snapshot_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnapshotOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_job_snapshots__snapshot_id__job_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                snapshot_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_snapshot_snapshots__snapshot_id__import_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                snapshot_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_import_snapshot_snapshots__snapshot_id__import_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnapshotOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    inbox_inbox_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InboxOut"];
                };
            };
        };
    };
    get_pack_snapshots__snapshot_id__pack_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                snapshot_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PackOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_block_route_snapshots__snapshot_id__blocks__block_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                snapshot_id: string;
                block_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_block_route_snapshots__snapshot_id__blocks__block_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                snapshot_id: string;
                block_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BlockUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProseBlockOut"] | components["schemas"]["FormulaBlockOut"] | components["schemas"]["TableBlockOut"] | components["schemas"]["FigureBlockOut"] | components["schemas"]["ListBlockOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_block_route_snapshots__snapshot_id__sections__section_id__blocks_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                snapshot_id: string;
                section_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BlockCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProseBlockOut"] | components["schemas"]["FormulaBlockOut"] | components["schemas"]["TableBlockOut"] | components["schemas"]["FigureBlockOut"] | components["schemas"]["ListBlockOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    process_snapshot_endpoint_snapshots__snapshot_id__process_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                snapshot_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnapshotOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
