"""s1 capture inbox

Revision ID: 00371ef138ba
Revises: 
"""
from alembic import op
import sqlalchemy as sa


revision = '00371ef138ba'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('locale', sa.Enum('zh', 'en', name='locale'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sources',
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Enum('snapshot', 'conversation', 'subscription', name='source_kind'), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('queued', 'processing', 'ready', 'awaiting_review', 'in_library', 'needs_attention', name='snapshot_status'), nullable=False),
    sa.Column('media_type', sa.Enum('article', 'pdf', 'video', 'podcast', 'note', 'screenshot', 'audio', 'webpage', name='media_type'), nullable=True),
    sa.Column('origin_url', sa.String(), nullable=True),
    sa.Column('content_body', sa.Text(), nullable=True),
    sa.Column('content_ref', sa.String(), nullable=True),
    sa.Column('captured_via', sa.Enum('share_sheet', 'wechat', 'email', 'in_app', 'paste', 'manual', 'screenshot', 'audio_memo', name='captured_via'), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sources_kind'), 'sources', ['kind'], unique=False)
    op.create_index(op.f('ix_sources_origin_url'), 'sources', ['origin_url'], unique=False)
    op.create_index(op.f('ix_sources_owner_id'), 'sources', ['owner_id'], unique=False)
    op.create_index(op.f('ix_sources_status'), 'sources', ['status'], unique=False)
    op.create_table('source_tags',
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('tag', sa.String(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_tags_source_id'), 'source_tags', ['source_id'], unique=False)
    # ### end Alembic commands ###
    op.execute(
        "INSERT INTO users (id, display_name, locale, created_at, updated_at) "
        "VALUES ('00000000-0000-0000-0000-000000000001', 'Dev', 'en', now(), now())"
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_source_tags_source_id'), table_name='source_tags')
    op.drop_table('source_tags')
    op.drop_index(op.f('ix_sources_status'), table_name='sources')
    op.drop_index(op.f('ix_sources_owner_id'), table_name='sources')
    op.drop_index(op.f('ix_sources_origin_url'), table_name='sources')
    op.drop_index(op.f('ix_sources_kind'), table_name='sources')
    op.drop_table('sources')
    op.drop_table('users')
    # ### end Alembic commands ###
