"""reader chat: pack_messages replaces pack_block_messages

Revision ID: 033e0b57ef69
Revises: f7a8b9c0d1e2
"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = '033e0b57ef69'
down_revision = 'f7a8b9c0d1e2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pack_messages',
    sa.Column('snapshot_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('user', 'assistant', name='chat_role', create_type=False), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('block_refs', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['snapshot_id'], ['sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pack_messages_snapshot_id'), 'pack_messages', ['snapshot_id'], unique=False)
    op.drop_index(op.f('ix_pack_block_messages_block_id'), table_name='pack_block_messages')
    op.drop_table('pack_block_messages')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pack_block_messages',
    sa.Column('block_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('role', postgresql.ENUM('user', 'assistant', name='chat_role', create_type=False), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['block_id'], ['pack_blocks.id'], name=op.f('pack_block_messages_block_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pack_block_messages_pkey'))
    )
    op.create_index(op.f('ix_pack_block_messages_block_id'), 'pack_block_messages', ['block_id'], unique=False)
    op.drop_index(op.f('ix_pack_messages_snapshot_id'), table_name='pack_messages')
    op.drop_table('pack_messages')
    # ### end Alembic commands ###
