"""s2 knowledge pack

Revision ID: cb5fcc8902ba
Revises: 00371ef138ba
"""
from alembic import op
import sqlalchemy as sa


revision = 'cb5fcc8902ba'
down_revision = '00371ef138ba'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Manually added: autogenerate does not detect enum-value additions.
    op.execute("ALTER TYPE snapshot_status ADD VALUE IF NOT EXISTS 'unprocessed'")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('concepts',
    sa.Column('concept_type', sa.Enum('idea', 'term', 'person', 'org', name='concept_type'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('aliases', sa.JSON(), nullable=True),
    sa.Column('definition', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_concepts_name'), 'concepts', ['name'], unique=False)
    op.create_table('concept_edges',
    sa.Column('from_concept_id', sa.Uuid(), nullable=False),
    sa.Column('to_concept_id', sa.Uuid(), nullable=False),
    sa.Column('relation', sa.Enum('related', 'part_of', 'contrasts', 'causes', 'example_of', name='concept_relation'), nullable=False),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['from_concept_id'], ['concepts.id'], ),
    sa.ForeignKeyConstraint(['to_concept_id'], ['concepts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_concept_edges_from_concept_id'), 'concept_edges', ['from_concept_id'], unique=False)
    op.create_index(op.f('ix_concept_edges_to_concept_id'), 'concept_edges', ['to_concept_id'], unique=False)
    op.create_table('cards',
    sa.Column('source_id', sa.Uuid(), nullable=True),
    sa.Column('card_type', sa.Enum('short_answer', 'mcq', 'cloze', 'explain', 'apply', 'recall', name='card_type'), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('origin', sa.Enum('pack', 'conversation', 'user', name='card_origin'), nullable=False),
    sa.Column('status', sa.Enum('draft', 'accepted', 'rejected', name='card_status'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cards_source_id'), 'cards', ['source_id'], unique=False)
    op.create_table('knowledge_packs',
    sa.Column('snapshot_id', sa.Uuid(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('background', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('generating', 'ready', name='pack_status'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['snapshot_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_packs_snapshot_id'), 'knowledge_packs', ['snapshot_id'], unique=True)
    op.create_table('source_concepts',
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('concept_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_concepts_concept_id'), 'source_concepts', ['concept_id'], unique=False)
    op.create_index(op.f('ix_source_concepts_source_id'), 'source_concepts', ['source_id'], unique=False)
    op.create_table('card_concepts',
    sa.Column('card_id', sa.Uuid(), nullable=False),
    sa.Column('concept_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_card_concepts_card_id'), 'card_concepts', ['card_id'], unique=False)
    op.create_index(op.f('ix_card_concepts_concept_id'), 'card_concepts', ['concept_id'], unique=False)
    op.create_table('pack_sections',
    sa.Column('pack_id', sa.Uuid(), nullable=False),
    sa.Column('heading', sa.String(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['pack_id'], ['knowledge_packs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pack_sections_pack_id'), 'pack_sections', ['pack_id'], unique=False)
    op.create_table('pack_blocks',
    sa.Column('section_id', sa.Uuid(), nullable=False),
    sa.Column('block_type', sa.Enum('prose', 'figure', 'callout', 'quote', name='pack_block_type'), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('content_ref', sa.String(), nullable=True),
    sa.Column('source_anchor', sa.JSON(), nullable=True),
    sa.Column('anchor_id', sa.String(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['section_id'], ['pack_sections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pack_blocks_anchor_id'), 'pack_blocks', ['anchor_id'], unique=False)
    op.create_index(op.f('ix_pack_blocks_section_id'), 'pack_blocks', ['section_id'], unique=False)
    op.create_table('pack_elements',
    sa.Column('pack_id', sa.Uuid(), nullable=False),
    sa.Column('element_type', sa.Enum('key_term', 'person_org', 'claim', 'counter_view', 'connection', name='pack_element_type'), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('concept_id', sa.Uuid(), nullable=True),
    sa.Column('block_id', sa.Uuid(), nullable=True),
    sa.Column('section_label', sa.String(), nullable=True),
    sa.Column('state', sa.Enum('suggested', 'kept', 'dismissed', name='pack_element_state'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['block_id'], ['pack_blocks.id'], ),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ),
    sa.ForeignKeyConstraint(['pack_id'], ['knowledge_packs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pack_elements_concept_id'), 'pack_elements', ['concept_id'], unique=False)
    op.create_index(op.f('ix_pack_elements_pack_id'), 'pack_elements', ['pack_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # Note: 'unprocessed' is left on snapshot_status — PostgreSQL has no DROP VALUE.
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pack_elements_pack_id'), table_name='pack_elements')
    op.drop_index(op.f('ix_pack_elements_concept_id'), table_name='pack_elements')
    op.drop_table('pack_elements')
    op.drop_index(op.f('ix_pack_blocks_section_id'), table_name='pack_blocks')
    op.drop_index(op.f('ix_pack_blocks_anchor_id'), table_name='pack_blocks')
    op.drop_table('pack_blocks')
    op.drop_index(op.f('ix_pack_sections_pack_id'), table_name='pack_sections')
    op.drop_table('pack_sections')
    op.drop_index(op.f('ix_card_concepts_concept_id'), table_name='card_concepts')
    op.drop_index(op.f('ix_card_concepts_card_id'), table_name='card_concepts')
    op.drop_table('card_concepts')
    op.drop_index(op.f('ix_source_concepts_source_id'), table_name='source_concepts')
    op.drop_index(op.f('ix_source_concepts_concept_id'), table_name='source_concepts')
    op.drop_table('source_concepts')
    op.drop_index(op.f('ix_knowledge_packs_snapshot_id'), table_name='knowledge_packs')
    op.drop_table('knowledge_packs')
    op.drop_index(op.f('ix_cards_source_id'), table_name='cards')
    op.drop_table('cards')
    op.drop_index(op.f('ix_concept_edges_to_concept_id'), table_name='concept_edges')
    op.drop_index(op.f('ix_concept_edges_from_concept_id'), table_name='concept_edges')
    op.drop_table('concept_edges')
    op.drop_index(op.f('ix_concepts_name'), table_name='concepts')
    op.drop_table('concepts')
    # ### end Alembic commands ###
